title: Fujia Qian
description: Systems Portfolio

theme: minima

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      sitemap: false

header_pages:
  - index.md

show_downloads: false